FROM rust:1.75-slim-buster

# Create a group and user with specified USER_ID and GROUP_ID
ARG HOST_UID=1000
ARG HOST_GID=1000
RUN groupadd -g ${HOST_GID} appuser && \
    useradd -m -u ${HOST_UID} -g appuser appuser


RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    libssl-dev \
    pkg-config \
    curl \
    && rm -rf /var/lib/apt/lists/*

USER appuser

WORKDIR /usr/src/storage-gateway

RUN cargo install cargo-watch

# Copy the Cargo.toml and Cargo.lock files to cache dependencies
COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock

# Build the dependencies
RUN mkdir src && \
    echo "fn main() {println!(\"if you see this, the build broke\")}" > src/main.rs && \
    cargo build && \
    rm -rf src

# Copy the source code
COPY . .

# Build the application
RUN cargo build

ENV RUST_LOG=info

CMD ["cargo", "watch", "-x", "run"]
