# Base stage
FROM rust:1.75-slim-buster

RUN apt-get update && apt-get install -y build-essential libpq-dev

ARG HOST_UID=1000
ARG HOST_GID=1000
RUN groupadd -g ${HOST_GID} appuser && \
    useradd -m -u ${HOST_UID} -g appuser appuser
USER appuser

WORKDIR /usr/src/storage-gateway

RUN cargo install diesel_cli --no-default-features --features postgres

COPY ./migrations ./migrations
