FROM rust:1.75-slim-buster

# Create a group and user with specified USER_ID and GROUP_ID
ARG HOST_UID=1000
ARG HOST_GID=1000
RUN groupadd -g ${HOST_GID} appuser && \
    useradd -m -u ${HOST_UID} -g appuser appuser

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    pkg-config \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/storage-gateway

RUN cargo install cargo-watch

COPY . .

RUN cargo build
CMD ["cargo", "watch", "-x", "run"]
