version: "3.8"
services:
  migration-runner:
    container_name: migration-runner
    build:
      context: ../storage-gateway/
      dockerfile: ../storage-gateway/Dockerfile.migration-runner
    command: sleep infinity
    volumes:
      - ../storage-gateway:/usr/src/storage-gateway
      - ./storage-gateway-config.yaml:/etc/storage-gateway/config.yaml
      - ./migration-runner-set-env.sh:/usr/src/storage-gateway/migration-runner-set-env.sh
    environment:
      - USER_ID=${HOST_UID:-1000}
      - GROUP_ID=${HOST_GID:-1000}
    depends_on:
      - postgres
    networks:
      - storage-gateway-network
    user: ${HOST_UID:-1000}:${HOST_GID:-1000}

  storage-gateway:
    container_name: storage-gateway
    build:
      context: ../storage-gateway/
      dockerfile: ../storage-gateway/Dockerfile.dev
    command: cargo watch -x run
    volumes:
      - ../storage-gateway:/usr/src/storage-gateway
      # Create a separate volume for the build directory so that the host's copy of cargo
      # doesn't interfere with the container. For example, I have an emacs plugin that
      # runs cargo check on save, which slows down the build in the container.
      - ../storage-gateway/container-target:/usr/src/storage-gateway/target
      - ./storage-gateway-config.yaml:/etc/storage-gateway/config.yaml
      - /home/john/.keys/hubs-dev-333333-8a27003a8831.json:/etc/storage-gateway/service-account.json
    environment:
      - USER_ID=${HOST_UID:-1000}
      - GROUP_ID=${HOST_GID:-1000}
      - SERVICE_ACCOUNT=/etc/storage-gateway/service-account.json
    depends_on:
      - postgres
    networks:
      - storage-gateway-network
    user: ${HOST_UID:-1000}:${HOST_GID:-1000}

  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: password
    volumes:
      - ../pgdata:/var/lib/postgresql/data
      - ./pg-init-storage-gateway.sh:/docker-entrypoint-initdb.d/pg-init-storage-gateway.sh
    networks:
      - storage-gateway-network

networks:
  storage-gateway-network:
    name: storage-gateway-network
    driver: bridge
