version: "3.8"
services:
  storage-gateway:
    container_name: storage-gateway
    build:
      context: ../storage-gateway/
      dockerfile: ../storage-gateway/Dockerfile.dev
    command: cargo watch -x run
    volumes:
      - ../storage-gateway:/usr/src/storage-gateway
      - ./storage-gateway-config.yaml:/etc/storage-gateway/config.yaml
    environment:
      - USER_ID=${HOST_UID:-1000}
      - GROUP_ID=${HOST_GID:-1000}
    depends_on:
      - postgres

    networks:
      - storage-gateway-network

  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: password
    volumes:
      - ../pgdata:/var/lib/postgresql/data
      - ./pg-init-storage-gateway.sh:/docker-entrypoint-initdb.d/pg-init-storage-gateway.sh
    networks:
      - storage-gateway-network

networks:
  storage-gateway-network:
    name: storage-gateway-network
    driver: bridge
